–## Часть 1: Введение в Pandas

Pandas - это библиотека Python для работы с данными. Она предоставляет мощные инструменты для анализа и манипуляции данными.

### Установка Pandas

Для начала убедитесь, что у вас установлена библиотека Pandas. Если ее нет, установите ее с помощью команды:

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dmbrtz/PycharmProjects/UrfuML/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/dmbrtz/PycharmProjects/UrfuML/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 6.1 MB/s eta 0:00:00a 0:00:01
Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 10.4 MB/s eta 0:00:00a 0:00:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

## Импорт библиотеки
Давайте начнем с импорта библиотеки Pandas:

In [3]:
import pandas as pd

## Часть 2: Работа с данными
### Чтение данных
Мы будем использовать датасет Titanic. Давайте прочитаем данные из CSV файла.

In [4]:
# Чтение данных из файла 'titanic.csv'
df = pd.read_csv('titanic.csv')

### Предпросмотр данных
Для первого ознакомления с данными давайте выведем первые несколько строк.

In [5]:
# Вывод первых 5 строк данных
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Информация о данных
Чтобы получить общую информацию о данных, воспользуйтесь методом .info().

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

### Работа с NaN
Часто данные содержат пропущенные значения, которые представляются как NaN (Not a Number). Pandas предоставляет удобные методы для работы с ними.

Проверка на наличие NaN. Методы fillna и dropna возвращают новые Dataframe, проверьте нет ли в них NaN

In [7]:
# Проверка на наличие NaN в DataFrame
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Заполнение NaN

In [8]:
# Заполнение NaN определенным значением (например, нулем)
# Используйте метод .fillna()
df_filled = df.fillna(0)

Удаление строк с NaN

In [9]:
# Удаление строк, содержащих NaN
# Используйте метод .dropna()
df_dropped = df.dropna()

## Часть 3: Обработка DataFrame
### Выбор данных
Pandas позволяет выбирать данные по индексам, меткам столбцов и условиям.

In [10]:
# Выбор столбца по метке
# Используйте синтаксис DataFrame['название_столбца']
df['City']

# Выбор нескольких столбцов
# Используйте синтаксис DataFrame[['столбец_1', 'столбец_2']]
df[['Name', 'Age']]

# Выбор строк по индексу
# Используйте метод .loc[]
df.loc[0:4]

# Выбор строк и столбцов по условию
# Используя логические операции, выберите мужчин старше 30
df[(df['Sex'] == 'male') & (df['Age'] > 30)]

KeyError: 'City'

### Сортировка данных
Сортировка данных по значениям столбцов.

In [11]:
# Сортировка данных по столбцу 'столбец_1' по возрастанию
# Используйте метод .sort_values()
df.sort_values(by='Age', ascending=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Группировка данных
Pandas также позволяет группировать данные и выполнять агрегирующие операции.

In [12]:
# Найдите долю выживших среди всех PClass
# Используйте метод .groupby()
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

## Часть 4: Задания для практики
Прочитайте данные из файла 'titanic.csv'.
Проверьте, есть ли пропущенные значения в данных и заполните их нулями.
Выведите первые 10 строк данных.
Выберите только те строки, где значение в столбце 'Age' больше 30.
Отсортируйте данные по столбцу 'Fare' в порядке убывания.
Сгруппируйте данные по столбцу 'Pclass' и вычислите средний возраст ('Age') для каждого класса.

In [16]:
df = pd.read_csv('titanic.csv')

print(f'invalid data: \n{df.isna().sum()}')
df_filled = df.fillna(0)
print(f'first 10 rows: \n{df_filled.head(10)}')

df_age_30 = df_filled[df_filled['Age'] > 30]
df_sorted = df_age_30.sort_values(by='Fare', ascending=False)

print(f'rows with age > 30, sorted by fare in ascending mode: \n{df_sorted}')

mean_age = df_filled.groupby('Pclass')['Age'].mean()
print(f'mean age in Pclass: \n{mean_age}')

invalid data:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
first 10 rows:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   0.0      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500     0        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250     0        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500     0        S
5      0            330877   8.4583     0        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750     0        S
8      2            347742  11.1333     0        S
9      0            237736  30.0708     0        C
rows with age > 30, sorted by fare in ascending mode:
     PassengerId  Survived  Pclass  \
258          259         1       1
679          680         1       1
737          738         1       1
438          439         0       1
299          300         1       1
..           ...       ...     ...
263          264         0       1
179          180         0       3
597          598         0       3
822          823         0       1
806          807         0       1

                                                Name     Sex   Age  SibSp  \
258                                 Ward, Miss. Anna  female  35.0      0
679               Cardeza, Mr. Thomas Drake Martinez    male  36.0      0
737                           Lesurer, Mr. Gustave J    male  35.0      0
438                                Fortune, Mr. Mark    male  64.0      1
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.0      0
..                                               ...     ...   ...    ...
263                            Harrison, Mr. William    male  40.0      0
179                              Leonard, Mr. Lionel    male  36.0      0
597                              Johnson, Mr. Alfred    male  49.0      0
822                  Reuchlin, Jonkheer. John George    male  38.0      0
806                           Andrews, Mr. Thomas Jr    male  39.0      0

     Parch    Ticket      Fare        Cabin Embarked
258      0  PC 17755  512.3292            0        C
679      1  PC 17755  512.3292  B51 B53 B55        C
737      0  PC 17755  512.3292         B101        C
438      4     19950  263.0000  C23 C25 C27        S
299      1  PC 17558  247.5208      B58 B60        C
..     ...       ...       ...          ...      ...
263      0    112059    0.0000          B94        S
179      0      LINE    0.0000            0        S
597      0      LINE    0.0000            0        S
822      0     19972    0.0000            0        S
806      0    112050    0.0000          A36        S

[305 rows x 12 columns]
mean age in Pclass:
Pclass
1    32.923241
2    28.091467
3    18.177026
Name: Age, dtype: float64